# Generated by Django 4.1.5 on 2023-01-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["catalog_number"]},
        ),
        migrations.AlterModelOptions(
            name="recordtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="style",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="artist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="can_con",
            field=models.BooleanField(default=False, verbose_name="CanCon"),
        ),
        migrations.AlterField(
            model_name="recordtype",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="style",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
